### ISSUE TITLE
Rework allocation of time 

### ISSUE THREAD

**Issue by SeanCraig** [arctangent-nhsuk/performance-management#1]
5.2 Nominal Time Allocation between activities

Look at presenting this in a different way despite this is what the DM's signed up to 
if 20% time was 20% of dev time then that would be .5 day per sprint [discuss]
Maybe work with some individuals / teams to take a lean(er) view and see what wasteful activities and improvements could be made

**Comment by arctangent** [comment]
Agree that we need a better presentation, and perhaps a "fairer" way to top-slice out activities we encourage (e.g. attendance at show and tells) so that we also "pay the price" for them.

Worth noting that the amount of 20% time available drives the amount of work we can expect devs to do for each Key Result agreed as part of the quarterly review cycle already in place:

> 1 Quarter = 12 weeks = 3 Objectives each with 4 Key Results

Smaller (or fewer) KRs means slower progress towards improving scores on the quality dashboard. There could be balancing benefits to less 20% time though e.g. more likelihood it will be "tolerated" by DMs and therefore more likely to happen...

**Comment by arctangent** [comment]
I have completely re-worked the approach in this commit: https://github.com/arctangent-nhsuk/performance-management/commit/4b349f5fe2b99f951c1f021cb2848ad65e7377a1

There is now a broad but hopefully useful categorisation of responsibilities and a matrix showing how progression through the bands results in an expanding set of responsibilities.

Instead of a detailed time allocation I've described a simple "golden rule" based on helping others and maximising value. (Careful examination of what I've produced suggests that it might be up to Principal Engineers to ensure sufficient "20% Time" work is taking place within teams, via their Engineering Quality Framework and Lean Improvement responsibilities...)

Closing this issue now with the expectation that further discussion about these changes will take place at DTLT on Monday.
